---
version: 2
enable-beta-ecosystems: true
updates:
-   package-ecosystem: github-actions
    directory: /
    schedule:
        interval: semiannually
    groups:
        actions-infrastructure:
            patterns:
            -   actions/*
-   package-ecosystem: gitsubmodule
    directory: /
    schedule:
        interval: semiannually
-   package-ecosystem: uv
    directory: /
    schedule:
        interval: semiannually
    groups:
        python:
            patterns:
            -   '*'
-   package-ecosystem: npm
    directory: /
    schedule:
        interval: semiannually
    groups:
        npm:
            patterns:
            -   '*'
