name: Feature request

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Suggest an idea for this website

body:

  - type: textarea
    attributes:
      label: Your idea
      description: When you suggest your idea, please try to supply (mock) examples!
