name: Read the Docs PR preview
on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  pr-preview-link:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "bids-website"
