---
name: BEP update reminder

on:
  schedule:
  # 1rst of may and november
  - cron: 0 0 1 5,11 *
  workflow_dispatch:

jobs:

  bep_update_reminder:

    runs-on: ubuntu-latest

    # only trigger update on upstream repo
    if: github.repository_owner == 'bids-standard'

    steps:
    - name: open issue
      uses: rishabhgupta/git-action-issue@v2
      id: Issue
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: BEP update reminder
          body: "Ask BEP leads for an update on the BEPs."
    - run: |
        echo ${{ steps.issue.outputs.issue }}
